name:         rbpcp-api
version:      '0.1.0.0'
synopsis:     RESTful Bitcoin Payment Channel Protocol Servant API description
category:     Finance Network Bitcoin
author:       Rune K. Svendsen
maintainer:   runesvend@gmail.com
license:      OtherLicense
license-file: LICENSE
github:       runeksvendsen/haskell-rbpcp-api
homepage:     http://paychandoc.runeks.me/

description: ! 'RESTful Bitcoin Payment Channel Protocol (RBPCP) allows a client to send Bitcoin
  payments to a server by establishing a Bitcoin payment channel with the server in a
  standardized manner.

  This library provides Servant API endpoints for RBPCP.

  API spec: http://paychandoc.runeks.me/'

default-extensions:
- OverloadedStrings
- MultiParamTypeClasses
- FlexibleInstances
- RecordWildCards
- DataKinds
- FlexibleContexts
- LambdaCase
- TypeOperators

dependencies:
- base                      >=4.7     && <5
- haskoin-core              >=0.4.0   && <0.5.0
- bitcoin-payment-protocol  >=0.1     && <0.2
- base16-bytestring         >=0.1.0   && <0.2.0
- bytestring                >=0.10.0  && <0.11.0
- cereal                    >=0.5.0   && <0.6.0
- text                      >=1.2.0   && <1.3.0
- aeson                     >=0.11.0  && <1.1
- string-conversions        >=0.4     && <0.5
- servant                   >=0.8     && <0.10
- servant-client            >=0.8     && <0.10
- time
- http-api-data

library:
  source-dirs: src
  exposed-modules:
  - RBPCP
  - RBPCP.Types
  - RBPCP.Api
  - RBPCP.Callback
  - RBPCP.Callback.Types
  - RBPCP.Callback.Api
