# resolver: lts-6.15
resolver: nightly-2016-12-05

packages:
## App
#- 'app-service-map'
- 'rbpcp-api'
- 'promissory-note-types'
- 'paychan-datastore'

## Extra deps
- location:
    git: https://github.com/runeksvendsen/haskoin.git
    commit: ddb3adbf59aa5a21c349e5db27ee977282036868
  extra-dep: true
  subdirs:
    - haskoin-core
    - haskoin-node
    - haskoin-wallet
- location:
    git: https://github.com/runeksvendsen/bitcoin-payment-channel.git
    commit: 4e911e973007c7679c8c194506490f984afde1cc
  extra-dep: true

- location:
    git: https://github.com/brendanhay/gogol.git
    commit: 93f392a2df332dd699528e7ea2422dc892d00971
  extra-dep: true
  subdirs:
    - gogol
    - core
    - gogol-datastore

- location:
    git: https://github.com/tsuraan/bytestring-arbitrary.git
    commit: ce6234d7204d8f1faa3a7c05f4802ead210245ce
  extra-dep: true



extra-deps:
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6
- cryptohash-sha256-0.11.100.1



flags: {}
extra-package-dbs: []
